export const yacht = [
    {
        title: 'YACHT 01',
        cabin: '7',
        guest: '14',
        crew: '18',
        length: '51',
        img_featured: '/img_featured.png',
    },
    {
        title: 'YACHT 02',
        cabin: '9',
        guest: '16',
        crew: '21',
        length: '55',
        img_featured: '/img_featured.png',
    },
    {
        title: 'YACHT 03',
        cabin: '6',
        guest: '12',
        crew: '18',
        length: '50',
        img_featured: '/img_featured.png',
    },
    {
        title: 'YACHT 04',
        cabin: '6',
        guest: '12',
        crew: '18',
        length: '50',
        img_featured: '/img_featured.png',
    },
    {
        title: 'YACHT 05',
        cabin: '6',
        guest: '12',
        crew: '18',
        length: '50',
        img_featured: '/img_featured.png',
    },
    {
        title: 'YACHT 06',
        cabin: '6',
        guest: '12',
        crew: '18',
        length: '50',
        img_featured: '/img_featured.png',
    },
    {
        title: 'YACHT 07',
        cabin: '6',
        guest: '12',
        crew: '18',
        length: '50',
        img_featured: '/img_featured.png',
    },
]